url: 'https://test-stand.gb.ru/gateway/login'
url2: 'https://test-stand.gb.ru/api/posts'
username: '1stud'
password: 'ef080ce410'
title: ABOUT SWEET BREAD
description: DESCRIPTION OF SWEET BREAD
content: A LOT OF SWEET BREAD